### ISSUE TITLE
[Bug]: once('update') not firing on new game after quitting to menu

### ISSUE THREAD

**Issue by SkyLover37** [skyrim-multiplayer/skymp#892] opened 2022-01-29 21:48 UTC
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

once('update') only fires on first load save/new game. If you load/new game after quitting to main menu the once('update') will not fire again.

SP 2.5.0/2.4.0

### OS

Windows

### OS version

10

### Skyrim version

1.5.97

### SKSE version

2.0.20

### client commit''s hash

N/A

### server commit''s hash

N/A

### Videocard model

RTX 3080

### Steps to reproduce

Have a plugin that prints a message inside once('update') 
load/start new game
quit to main menu
start new game

### Expected result

For once('update') to trigger on any new game.

### Actual result

It did not.

**Comment by kkEngine** [comment] 2022-01-31 07:47
It is not a bug. "once" should firing only once :)
You can try use this event:
`
on("loadGame", () => printConsole("helloWorld"))
`

**Comment by SkyLover37** [comment] 2022-02-01 00:39
loadGame does not fire on a new game. Hence me calling that once not firing on a new game a bug. As using once() for anything initialization wise is worthless otherwise. The recipe that says to use once for initialization should be changed or have a warning put on it otherwise.

**Comment by Pospelove** [comment] 2022-04-03 23:53
Well, it's not a bug of `once('update')` so closing. Please if it is still an issue ask on our Discord server. I think folks know a workaround

**Closed by Pospelove** 2022-04-03 23:53 UTC
Labels: bug-report
