### ISSUE TITLE
Problem with CEF installation

### ISSUE THREAD

**Issue by TheLifeWorm** [skyrim-multiplayer/skymp#83] opened 2021-07-19 13:15 UTC
Аn error occurs when i starting configuring project.
No log file is created.
```
E:\SkyMP\skymp\build>cmake ..
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- Unexpected CEF README hash
        Expected: dbaa71607debbba411f9ce4c8e28ca52ba98676ebf11db25d2ba0e47b686c7ec9b30bfc34bdd7ff665e3b79cb863c85639585bd6d945c86f1b28fee548452c47
        Actual:
-- Installing CEF
-- Downloading...
-- Extracting archive...
-- Found CEF:
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package):
  By not providing "FindCEF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CEF", but
  CMake did not find one.

  Could not find a package configuration file provided by "CEF" with any of
  the following names:

    CEFConfig.cmake
    cef-config.cmake

  Add the installation prefix of "CEF" to CMAKE_PREFIX_PATH or set "CEF_DIR"
  to a directory containing one of the above files.  If "CEF" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  skyrim-platform/src/platform_se/CMakeLists.txt:21 (find_package)


-- Configuring incomplete, errors occurred!

E:\SkyMP\skymp\build>
```

CEF folder in build is empty.

**Comment by Pospelove** [comment] 2021-07-19 19:18
What happens if you retry CMake command?

**Comment by TheLifeWorm** [comment] 2021-07-20 09:42
> What happens if you retry CMake command?

Exactly the same
```
E:\SkyMP\skymp\build>cmake ..
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- Unexpected CEF README hash
        Expected: dbaa71607debbba411f9ce4c8e28ca52ba98676ebf11db25d2ba0e47b686c7ec9b30bfc34bdd7ff665e3b79cb863c85639585bd6d945c86f1b28fee548452c47
        Actual:
-- Installing CEF
-- Downloading...
-- Extracting archive...
-- Found CEF:
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package):
  By not providing "FindCEF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CEF", but
  CMake did not find one.

  Could not find a package configuration file provided by "CEF" with any of
  the following names:

    CEFConfig.cmake
    cef-config.cmake

  Add the installation prefix of "CEF" to CMAKE_PREFIX_PATH or set "CEF_DIR"
  to a directory containing one of the above files.  If "CEF" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  skyrim-platform/src/platform_se/CMakeLists.txt:21 (find_package)


-- Configuring incomplete, errors occurred!

E:\SkyMP\skymp\build>
```

**Comment by Pospelove** [comment] 2021-07-20 23:17
> > What happens if you retry CMake command?
> 
> Exactly the same
> 
> ```
> E:\SkyMP\skymp\build>cmake ..
> -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
> -- Unexpected CEF README hash
>         Expected: dbaa71607debbba411f9ce4c8e28ca52ba98676ebf11db25d2ba0e47b686c7ec9b30bfc34bdd7ff665e3b79cb863c85639585bd6d945c86f1b28fee548452c47
>         Actual:
> -- Installing CEF
> -- Downloading...
> -- Extracting archive...
> -- Found CEF:
> CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package):
>   By not providing "FindCEF.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "CEF", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "CEF" with any of
>   the following names:
> 
>     CEFConfig.cmake
>     cef-config.cmake
> 
>   Add the installation prefix of "CEF" to CMAKE_PREFIX_PATH or set "CEF_DIR"
>   to a directory containing one of the above files.  If "CEF" provides a
>   separate development package or SDK, be sure it has been installed.
> Call Stack (most recent call first):
>   skyrim-platform/src/platform_se/CMakeLists.txt:21 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> 
> E:\SkyMP\skymp\build>
> ```

Hm. What is your CMake version? Use `cmake --version` to check

**Comment by Pospelove** [comment] 2021-07-20 23:19
Btw CEF installation goes here https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/CMakeLists.txt#L27
You can try to debug the error here. Unfortunately, for now, I can't reproduce this bug.

**Comment by TheLifeWorm** [comment] 2021-07-21 09:03
> > > What happens if you retry CMake command?
> > 
> > 
> > Exactly the same
> > ```
> > E:\SkyMP\skymp\build>cmake ..
> > -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
> > -- Unexpected CEF README hash
> >         Expected: dbaa71607debbba411f9ce4c8e28ca52ba98676ebf11db25d2ba0e47b686c7ec9b30bfc34bdd7ff665e3b79cb863c85639585bd6d945c86f1b28fee548452c47
> >         Actual:
> > -- Installing CEF
> > -- Downloading...
> > -- Extracting archive...
> > -- Found CEF:
> > CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package):
> >   By not providing "FindCEF.cmake" in CMAKE_MODULE_PATH this project has
> >   asked CMake to find a package configuration file provided by "CEF", but
> >   CMake did not find one.
> > 
> >   Could not find a package configuration file provided by "CEF" with any of
> >   the following names:
> > 
> >     CEFConfig.cmake
> >     cef-config.cmake
> > 
> >   Add the installation prefix of "CEF" to CMAKE_PREFIX_PATH or set "CEF_DIR"
> >   to a directory containing one of the above files.  If "CEF" provides a
> >   separate development package or SDK, be sure it has been installed.
> > Call Stack (most recent call first):
> >   skyrim-platform/src/platform_se/CMakeLists.txt:21 (find_package)
> > 
> > 
> > -- Configuring incomplete, errors occurred!
> > 
> > E:\SkyMP\skymp\build>
> > ```
> 
> Hm. What is your CMake version? Use `cmake --version` to check

```
E:\SkyMP\skymp\build>cmake --version
cmake version 3.21.0-rc1
```

**Comment by Pospelove** [comment] 2021-07-21 09:06
@TheLifeWorm 
CMake 3.21.0 isn't supported currently. See readme and https://github.com/skyrim-multiplayer/skymp/issues/62
Try building with CMake 3.20

**Comment by Pospelove** [comment] 2021-07-23 21:57
@TheLifeWor How is it going?

**Comment by Pospelove** [comment] 2021-07-29 01:16
Closing for now. feel free to reopen if it's still a problem

**Closed by Pospelove** 2021-07-29 01:16 UTC
Labels: bug
