### ISSUE TITLE
Ensure that JsEngine is initialized before calling DynamicFields::GetAsJson() 

### ISSUE THREAD

**Issue by alekcey0211** [skyrim-multiplayer/skymp#53] opened 2021-07-10 12:18 UTC
When i use mp.set for non-default property i get this error.
```
Error: 'JsGetGlobalObject' returned error 0x10003
```
I think this behavior should not.

**Comment by alekcey0211** [comment] 2021-09-05 05:52
Maybe you can try to fix this error? It is very critical for all players, all progress is reset when the server restarts.

If you add try catch in DynamicFields.cpp the file is like this
```cpp
const nlohmann::json& DynamicFields::GetAsJson() const
{
  ...
    for (auto& [key, v] : pImpl->props) {
        try {
          obj[key] = JsValueToJson(v);
        } catch (...) {}
    }
  ...
}
```
then at least you don't have to choose a race from scratch, but the accumulated things disappear
maybe this example of a fix will somehow suggest a solution to the problem

**Comment by Pospelove** [comment] 2021-09-05 09:03
@alekcey0211 I guess you are testing with custom functions-lib and place something that can't be JSON-serialized into property values. We do not provide support to modified servers at this moment. Consider reviewing the code on your side or waiting for us to trigger this behavior and fixing it.

**Comment by alekcey0211** [comment] 2021-09-05 11:19
that is, not all data types can be used? is there a list of values that we can use? number string object?

**Comment by alekcey0211** [comment] 2021-09-05 13:29
and what if I say that in your functions-lib, you can also crash the server with the error 'Js Get Global Object' returned error 0x10003
if you add `mp.set(pcFormId, 'browserFocused', true);` in uiEvent and if you send a message via chat, you will get an error and then the entry in the database stops working
```ts
 mp['onUiEvent'] = (pcFormId: number, uiEvent: Record<string, unknown>) => {
  ...
        if (typeof text === 'string') {
          const ac: PapyrusObject = { type: 'form', desc: mp.getDescFromId(pcFormId) };
          mp.set(pcFormId, 'browserFocused', true);
          mp.callPapyrusFunction('global', 'GM_Main', '_OnChatInput', null, [ac, text]);
        }
    ...
  };
```

**Comment by Pospelove** [comment] 2021-11-30 00:20
Closing as duplicate of #51. feel free to reopen if the problem still exists

**Closed by Pospelove** 2021-11-30 00:20 UTC
Labels: temporarily unsupported
